name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: print date with long format
        run: |
          date +"%A, %B %d, %Y"
      - name : list directory with ls -l
        run: |
          ls -l